
version: "3.8"

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: crf
      POSTGRES_PASSWORD: crfpass
      POSTGRES_DB: crf
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # api:
  #   build: ./api
  #   environment:
  #     - DATABASE_URL=postgres://crf:crfpass@db:5432/crf
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - "5000:5000"

  # web:
  #   build: ./web
  #   depends_on:
  #     - api
  #   ports:
  #     - "5173:5173"
